### ISSUE TITLE
Problem on status page

### ISSUE THREAD

**Issue by berrabe** [lucasheld/ansible-uptime-kuma#13]
i've problem when i want to add new status page with `status` and `status page info` module, there is error with the sqlite, here's the error log

```uptime_kuma_api.exceptions.UptimeKumaException: insert into \`status_page\` (\`icon\`, \`slug\`, \`theme\`, \`title\`) values ('', 'xxx-monitoring', 'light', 'xxx-monitoring') - SQLITE_CONSTRAINT: UNIQUE constraint failed: status_page.slug```

and here's my screenshot
![image](https://user-images.githubusercontent.com/34432326/213967790-fc7c454f-c611-418a-b16e-71979f70552f.png)

**Comment by lucasheld** [comment]
Unfortunately, I cannot reproduce the problem.

Maybe the following exception is too broad.
If a status page does not exist, an exception is raised and a new status page will be created. In your case, maybe the status page exists and the exception is raised for a different reason.

https://github.com/lucasheld/ansible-uptime-kuma/blob/e1af0d6e5beebe89331bd339e8b7182ecb180603/plugins/modules/status_page.py#L188-L191

You can try to edit the module `~/.ansible/collections/ansible_collections/lucasheld/uptime_kuma/plugins/modules/status_page.py` and replace the code with:
```python
    try: 
        status_page = api.get_status_page(slug) 
    except Exception:
        import traceback
        result["exception"] = traceback.format_exc()
        status_page = None
```

Then run your playbook again and check the error message. The first line should contain the exception message.

**Comment by berrabe** [comment]
oke here's my update (**NOTE: i'm using Uptime Kuma Version: 1.19.6**)

i've changed your ansible python module with your snippet code, and here's the screenshot
![image](https://user-images.githubusercontent.com/34432326/214241448-6c6205d0-1ab3-4077-893d-ee77b044ae9d.png)

as you can see, i think the problem is on sqlite, because the exception shows SQLite error regarding constraint
```sql
uptime_kuma_api.exceptions.UptimeKumaException: insert into `status_page` (`icon`, `slug`, `theme`, `title`) values ('', 'test-ansible', 'light', 'test-ansible') - SQLITE_CONSTRAINT: UNIQUE constraint failed: status_page.slug
```

**Comment by lucasheld** [comment]
The SQL error occurs because the status page already exists and the module is trying to add a new one. This causes the SQL error because this slug is already in use. The actual problem is the JSONDecodeError in the first line.
Please execute the playbook again and add the parameter `-vvv` as mentioned in the first line of the error message.
Then post the error message again. This new error message contains the traceback of the JSONDecodeError. There we can see in which line the exception is raised.

**Comment by lucasheld** [comment]
Could you find out what is causing the problem?
