### ISSUE TITLE
Role installation error

### ISSUE THREAD

**Issue by etpedro** [lucasheld/ansible-uptime-kuma#16]
Hi @lucasheld 

I'm trying to install the ansible role as stated and I get the following errors:

$ ansible --version
ansible 2.9.6

$ ansible-galaxy --version
ansible-galaxy 2.9.6

$ ansible-galaxy collection install git+https://github.com/lucasheld/ansible-uptime-kuma.git
Process install dependency map
ERROR! Invalid collection name 'git+https', name must be in the format <namespace>.<collection>. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.

$ ansible-galaxy role install -fgr requirements.yml
[WARNING]: - ansible-uptime-kuma was NOT installed successfully: this role does not appear to have a meta/main.yml file.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

Can you please help?

**Comment by lucasheld** [comment]
I think you can fix this problem by upgrading your ansible version. This functionality was introduced in 2.10.

You can use pip for that: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#pip-install

**Comment by etpedro** [comment]
That was it! I read several foruns saying it was only introduced in 2.10 but the version on ubuntu native ppa was only till 2.9.6.
This made the trick: https://www.ansiblepilot.com/articles/how-to-install-ansible-in-ubuntu-21.10-ansible-install/

Thank you very much for your support!
