### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by confiar** [lucasheld/ansible-uptime-kuma#22]
it's not working.
please help me.

An error occurs when I enter the command below.

ansible-galaxy collection install git+https://github.com/lucasheld/ansible-uptime-kuma.git

ERROR! Invalid collection name 'git+https', name must be in the format .. Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.

**Comment by lucasheld** [comment]
See https://github.com/lucasheld/ansible-uptime-kuma/issues/16
Check your Ansible version. You need at least 2.10.
