### ISSUE TITLE
Add Monitor type Group

### ISSUE THREAD

**Issue by CygnusHyoga** [lucasheld/ansible-uptime-kuma#27]
First of all thanks for this fantastic collection/module!!! :-)

I want to create a monitor type group in lucasheld.uptime_kuma.monitor, but I don't see type: group in the documentation. I see that I can add monitor to parent (and its work great), but I don't see how ti create a group monitor.

How we create a monitor group? Its supported or its planned for future support? 

Thanks!

**Comment by CygnusHyoga** [comment]
I tried to add a group, with type group and it's worked fine :-)

Maybe it's recommended to add this to the documentation.

https://github.com/lucasheld/ansible-uptime-kuma/wiki/monitor

**Comment by lucasheld** [comment]
Yes, I forgot to add the type to the documentation. Thanks!
