### ISSUE TITLE
Status page: show clickable URL

### ISSUE THREAD

**Issue by TheLastProject** [lucasheld/ansible-uptime-kuma#30]
I think it would be great if we could set the "show clickable URL" setting on a monitor in the status page:

![image](https://github.com/lucasheld/ansible-uptime-kuma/assets/1885159/e2c35843-f871-433b-804d-865865d70c35)

**Comment by obfusk** [comment]
Unless I overlooked something (I haven't tested this, just looked at the code), I think for that to work, `sendUrl` would need to be added to both of these (and the documentation):

* [`ansible-uptime-kuma/plugins/modules/monitor.py` ->`main()` -> `module_args`](https://github.com/lucasheld/ansible-uptime-kuma/blob/master/plugins/modules/monitor.py#L413)
* [`kuma-api/uptime_kuma_api/api.py` -> `_build_monitor_data()`](https://github.com/lucasheld/uptime-kuma-api/blob/master/uptime_kuma_api/api.py#L640)

**Comment by TheLastProject** [comment]
Sorry, those links aren't correct. It's not a monitor setting, it's a setting for an entry in the monitorList on the status page: https://github.com/lucasheld/ansible-uptime-kuma/wiki/status_page

**Comment by obfusk** [comment]
You are correct. It looks like the only change needed is [`ansible-uptime-kuma/plugins/modules/status_page.py` -> `main()` -> `module_args`](https://github.com/lucasheld/ansible-uptime-kuma/blob/master/plugins/modules/status_page.py#L241).

**Comment by obfusk** [comment]
AFAICT `sendUrl` *is* part of the monitor model in Uptime Kuma, which is why I thought it needed to be set there, but indeed to *set* it requires providing it via `monitorList` in `saveStatusPage`. Thanks for pointing that out :)

**Comment by obfusk** [comment]
We seem to be having a strange bug on our end after we tried using this. Unfortunately, we can't debug for another week. Will get back to you.

**Comment by lucasheld** [comment]
@obfusk
Does the problem still exist? What kind of bug is it?

**Comment by obfusk** [comment]
@TheLastProject reported getting an error. But I tested it today and it seems to work fine :)
