### ISSUE TITLE
Support http(s) - Json Query Monitor

### ISSUE THREAD

**Issue by TheLastProject** [lucasheld/ansible-uptime-kuma#33]
It would be great if the Json Query monitor introduced in [1.23.0](https://github.com/louislam/uptime-kuma/releases/tag/1.23.0) could be supported. No rush of course, thanks for this great project :heart:

**Comment by lucasheld** [comment]
I first need to support this version in the python module (https://github.com/lucasheld/uptime-kuma-api/issues/49). Then I will implement the changes in the Ansible collection.

**Comment by lucasheld** [comment]
Uptime Kuma 1.23.1 is supported in version 1.2.0.
